// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm86I062dZ_cwpyTMwWwPKjMGDcOOgtNU',
    appId: '1:170776275984:web:82347860baf2fb9abb6e95',
    messagingSenderId: '170776275984',
    projectId: 'autotricks-6485f',
    authDomain: 'autotricks-6485f.firebaseapp.com',
    storageBucket: 'autotricks-6485f.firebasestorage.app',
    measurementId: 'G-9NEGCDPG9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-aKyMVMPEDHKToVuxcUvKw0yHYEkHxA',
    appId: '1:170776275984:android:baea716f3bcb680bbb6e95',
    messagingSenderId: '170776275984',
    projectId: 'autotricks-6485f',
    storageBucket: 'autotricks-6485f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpqjFXbMe6nTgrsKBXlniekzHt82r_ASY',
    appId: '1:170776275984:ios:2c9e3341bce51111bb6e95',
    messagingSenderId: '170776275984',
    projectId: 'autotricks-6485f',
    storageBucket: 'autotricks-6485f.firebasestorage.app',
    iosBundleId: 'com.autotricks.autotricks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm86I062dZ_cwpyTMwWwPKjMGDcOOgtNU',
    appId: '1:170776275984:web:380721d8cf423ff4bb6e95',
    messagingSenderId: '170776275984',
    projectId: 'autotricks-6485f',
    authDomain: 'autotricks-6485f.firebaseapp.com',
    storageBucket: 'autotricks-6485f.firebasestorage.app',
    measurementId: 'G-QFY1EXRSDX',
  );
}
